### ISSUE TITLE
Double Decoding Of Value

### ISSUE THREAD

**Issue by zeWizard** [Efferent-Health/HL7-dotnetcore#120] opened 2023-11-16 11:27 UTC
**Summary**
It appears as though when you use the message.GetValue function it is actually double decoding the value.

**Example**
When trying to retrieve a value from a Message that has encoded characters. For example an RTF body 

```
{\rtf1\ansi\ansicpg1252\uc1\deff1\adeff1\
```

The value will come through like the following on the HL7 Message: 

```
{\E\rtf1\E\ansi\E\ansicpg1252\E\uc1\E\deff1\E\adeff1\E\
```

As expected.

However, when you use the GetValue function on the message like so:

```
var message = new Message("MSH|^~\&|Best Practice 1.......");
message.ParseMessage();
var observationResultText = message.GetValue("OBX(1).5");
```

The obx text is returned as follows

```
{rtf1ansiansicpg1252uc1deff1adeff1
```

because it has double decoded the data. Notice the missing \

**Reason**

This is because the GetValue function actually gets a decoded value on MessageElement which already decodes the data:

```
  public  string Value 
  { 
      get 
      {
          return _value == Encoding.PresentButNull ? null : Encoding.Decode(_value); 
      }
      set 
      { 
          _value = value; 
          ProcessValue(); 
      }
  }
```

see **_Encoding.Decode(_value);_** 

and then at the end of the GetValue function it decodes it again

```
            return this.Encoding.Decode(strValue);
```

and see **_this.Encoding.Decode(strValue);_**

**Comment by jaime-olivares** [comment] 2024-06-18 20:55
Hi @zeWizard,
I just merged issue #117 that also refers to a double-encoding issue.
Please check if it solves your problem. Otherwise, I will need a full test in your PR.

**Comment by jaime-olivares** [comment] 2024-06-18 21:22
use version https://www.nuget.org/packages/HL7-dotnetcore/2.37.0

**Comment by jaime-olivares** [comment] 2024-06-27 19:02
As there are not more comments to this, I am closing it, including the related PR.
I assume the issue is already solved by another PR.
In case you want to fully confirm, please post a full TestMethod.

**Closed by jaime-olivares** 2024-06-27 19:02 UTC
